from effects.blinking import apply_blinking_effect
from effects.make_video import create_video_from_image
from effects.tv_filter import tv_filter
from effects.red_shade import create_red_box_animation
from effects.shake import shake
from effects.circle import translate_in_circle
from effects.shake_switch import switch_images_with_vibration
from effects.grey_image_in_window import grey_image_in_window_vibrate_and_shifts
